In [1]:
import numpy as np

Basic Array creation

In [2]:
arr = np.array([1,2,3,4])

array([1, 2, 3, 4])

In [4]:
a = [1,2,3.5,"hello"]
a

[1, 2, 3.5, 'hello']

In [5]:
np.array(a)

array(['1', '2', '3.5', 'hello'], dtype='<U32')

In [6]:
l = [[1,2,3],[4,5,6]]

In [7]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6]])

Above 2D are the tensors

Array generation function

In [11]:
arr = np.arange(1,10,2)
arr

array([1, 3, 5, 7, 9])

In [15]:
arr = np.zeros((4,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [16]:
arr = np.ones(2)
arr

array([1., 1.])

In [20]:
arr = np.linspace(1,5,5)
arr

array([1., 2., 3., 4., 5.])

Random Generation Function

In [21]:
np.random.rand(10)

array([0.3228974 , 0.68248311, 0.21443029, 0.72242927, 0.09967724,
       0.15612236, 0.93612686, 0.23502794, 0.17240076, 0.22553165])

In [22]:
np.random.randn(10)

array([-0.8360688 , -0.14725565,  1.08497793, -0.51429995, -1.41152308,
       -0.72791082, -1.79740955,  0.41382222, -2.08104383, -0.15346213])

In [27]:
np.random.randint(10,20,10)

array([16, 19, 12, 11, 14, 13, 12, 11, 13, 10], dtype=int32)

Array Attributes

In [33]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
arr.shape

(3, 3)

In [35]:
arr.size

9

In [36]:
arr.dtype

dtype('int64')

Array Methods

In [37]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
arr.min()

np.int64(1)

In [40]:
arr.max()

np.int64(9)

In [42]:
arr.sum()

np.int64(45)

In [43]:
np.sum(arr,axis=0)

array([12, 15, 18])

In [44]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [45]:
arr.mean()

np.float64(5.0)

In [47]:
arr.std()

np.float64(2.581988897471611)

In [48]:
arr.argmax()

np.int64(8)

In [49]:
arr.argmin()

np.int64(0)

Reshaping and Resizing

In [51]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [56]:
arr = arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

 ARRAY INDEXING 

In [62]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [63]:
arr[6]

np.int64(17)

In [65]:
arr[:5]

array([11, 12, 13, 14, 15])

In [68]:
arr_s= arr[3::2]
arr_s

array([14, 16, 18, 20])

NUMPY Indexing and slicing of matrix

In [72]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [73]:
arr[0]

array([1, 2, 3, 4, 5])

In [74]:
arr[0][0]

np.int64(1)

In [75]:
arr[0,0]

np.int64(1)

In [77]:
slice = arr[0:2,1:3]
slice

array([[2, 3],
       [7, 8]])

In [81]:
slice2 = arr[3:6,3:5]
slice2

array([[19, 20],
       [24, 25],
       [29, 30]])

In [82]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

Boolean Indexing

In [84]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [89]:
bool_index = arr%2==0
bool_index

array([ True,  True,  True,  True,  True])

In [90]:
arr = arr[bool_index]
arr


array([12, 14, 16, 18, 20])

Array Operation

In [91]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [92]:
a1 + a2

array([ 7,  9, 11, 13, 15])

Broadcasting

In [95]:
l = [10,20,30,40]
arr = np.array(l)

In [96]:
arr + 10

array([20, 30, 40, 50])

Deep & Shallow Copy

In [98]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [99]:
arr2+10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [101]:
arr2*2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50]])

 Matrix Operations

In [111]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [113]:
A @ B

array([[19, 22],
       [43, 50]])

In [114]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [115]:
A.T

array([[1, 3],
       [2, 4]])

Advanced Array Operation

Stacking Array

In [116]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [117]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [118]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [119]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

Splitting Array

In [121]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [122]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [124]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [125]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

Valid Sudoku

In [ ]:
S = np.array()